.TH LOGDISSECT 3
.SH NAME
The logdissect module contains utilities for parsing, filtering, and exporting syslog data.

.SH SYNOPSIS
    \fBimport logdissect
    myparser = logdissect.parsers.syslogbsd.ParseModule()
    attribute_dict = myparser.parse_line(\fI<RAW_LINE>\fB)
    logdataobject = myparser.parse_log(\fI<LOG_FILE_PATH>\fB)
    logentryobject = logdissect.data.LogEntry()

.SH DESCRIPTION
The logdissect module comes with the logdissect log analysis program. It contains objects which can be used to parse log lines and files, and store log information.

.SH PARSERS
\fBlogdissect.parsers.<parser>.ParseModule()\fR
.br
Replace <parser> with one of the available parsers:
    \fBsyslogbsd\fR - standard syslog
    \fBsyslogiso\fR - syslog with ISO 8601 datestamp
    \fBnohost\fR - syslog with no host attribute
    \fBtcpdump\fR - tcpdump terminal output
    \fBldjson\fR - logdissect JSON output
    
Parsers have two methods (except the ldjson parser, which has no parse_line() method):

\fBparse_file(\fI<file>\fB)\fR
.br
Accepts a filename as input, and returns a LogData object (described below).

Parsers have a tzone attribute that uses standard ISO 8601 offset to UTC (e.g. '+0500', '-0200'); if not set, logdissect will attempt to get current time zone data from the local system (unless a time zone is already present, such as in the syslogiso parser, or the ldjson parser).

\fBparse_line(\fI<line>\fB)\fR
.br
Accepts a log line as input, and returns a dictionary of strings containing the following keys:

\fByear\fR - a 4-digit string
\fBmonth\fR - a 2-digit string
\fBday\fR - a 2-digit string
\fBtstamp\fR - a 6-digit string with optional decimal and extra places
\fBtzone\fR - \fB+\fR or \fB-\fR followed by a 4-digit offset to utc (HHMM)
\fBraw_stamp\fR - the raw stamp with attributes, as it was parsed
\fBfacility\fR - the log facility
\fBseverity\fR - the severity
\fBsource_host\fR - the source host
\fBsource_port\fR - the source port
\fBsource_process\fR - the source process
\fBsource_pid\fR - the source PID
\fBdest_host\fR - the destination host
\fBdest_port\fR - the destination port
\fBprotocol\fR - the protocol
\fBmessage\fR - the message

Attributes that were not parsed will be returned as \fBNone\fR. The ldjson parser has no parse_line() method.

.SH DATA OBJECTS
\fBlogdissect.data.LogEntry()\fR
.br
LogEntry is the data type for a single log entry. LogEntry objects have the following attributes:
    \fBparser\fR
    \fBdate_stamp_noyear\fR
    \fBdate_stamp\fR
    \fBdate_stamp_utc\fR
    \fBtzone\fR
    \fBraw_text\fR
    \fBraw_stamp\fR
    \fBfacility\fR
    \fBseverity\fR
    \fBmessage\fR
    \fBsource_path\fR - the file it was parsed from
    \fBsource_host\fR
    \fBsource_port\fR
    \fBsource_process\fR
    \fBsource_pid\fR
    \fBdest_host\fR
    \fBdest_port\fR
    \fBprotocol\fR

LogEntry objects have one method:
    \fB_utc_date\fR - uses datestamp and tzone attributes to to extrapolate date_stamp_utc

\fBlogdissect.data.LogData()\fR
.br
LogData is the data type for a single log. LogData objects have the following attributes:
    \fBentries\fR - a list containing LogEntry objects
    \fBsource_path\fR - the file it was parsed from
    \fBsource_file\fR
    \fBsource_file_mtime\fR
    \fBparser\fR

LogData objects have a few sorting methods:    
    \fBsort_time()\fR - sorts entries by their date_stamp_utc attribute
    \fBsort_path()\fR - sorts by path
    \fBsort_facility\fR - sorts by facility, then severity.

\fBlogdissect.data.LogDataSet()\fR
.br
LogDataSet is the data type for a logdissect project. LogDataSet objects have the following attributes:
    \fBdata_set\fR - a list containing LogData objects
    \fBfinalized_data\fR - a LogData object to hold all of the hold logs

LogDataSet objects have one method:
    \fBmerge_logs()\fR - merges the logs in data_set into finalized_data, and sorts them using LogData's sort_time() method

.SH SEE ALSO
    logdissect(1)

.SH FILES
    /usr/share/doc/logdissect/README.md
    /usr/share/doc/logdissect/README-API.md
    /usr/share/doc/logdissect/README-DEV.md
    /usr/share/doc/logdissect/CHANGELOG.md
    /usr/share/doc/logdissect/LICENSE

.SH AUTHOR
    Dan Persons (dpersonsdev@gmail.com)

.SH COPYRIGHT
MIT License

Copyright (c) 2017 Dan Persons

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
