.TH LOGDISSECT 3
.SH NAME
The logdissect module contains utilities for parsing, filtering, and exporting syslog data.

.SH SYNOPSIS
    \fBimport logdissect
    myparser = logdissect.parsers.syslogbsd.ParseModule()
    attribute_dict = myparser.parse_line(\fI<RAW_LINE>\fB)
    logdataobject = myparser.parse_log(\fI<LOG_FILE_PATH>\fB)
    logentryobject = logdissect.data.LogEntry()

.SH DESCRIPTION
The logdissect module comes with the logdissect log analysis program. It contains objects which can be used to parse log lines and files.

.SH PARSERS
\fBlogdissect.parsers.<parser>.ParseModule()\fR
.br
Replace <parser> with one of the available parsers:
    \fBciscoios\fR - Cisco IOS logs
    \fBsyslog\fR - standard syslog
    \fBsyslogiso\fR - syslog with ISO 8601 datestamp
    \fBsyslognohost\fR - syslog with no host attribute
    \fBtcpdump\fR - tcpdump terminal output
    \fBsojson\fR - logdissect single-object JSON output
    \fBlinejson\fR - logdissect object-per-line JSON output
    \fBwindowsrsyslog\fR - Windows rsyslog agent forwarded logs
    
Parsers have two methods (except the sojson parser, which has no parse_line() method):

\fBparse_file(\fI<file>\fB)\fR
.br
Accepts a filename as input, and returns a dictionary with some metadata, and a list of entry dictionaries (`entries`).

Parsers have a \fBtzone\fR attribute that uses standard ISO 8601 offset to UTC (e.g. \fB+0500\fR, \fB-0200\fR); if not set, logdissect will attempt to get current time zone data from the local system (unless a time zone is already present, such as in the syslogiso parser, or the sojson parser).

\fBparse_line(\fI<line>\fB)\fR
.br
Accepts a log line as input, and returns a dictionary of strings. There are two built-in keys, \fBraw_text\fR and \fBparser\fR, and parsers can add their own keys.

Parsers have a \fBdatestamp_type\fR attribute that defines how timestamps will be converted. The options are as follows:

    \fB`standard`\fR - Standard syslog date stamps
    \fB`nodate`\fR - Time stamps with no date (i.e. tcpdump)
    \fB`iso`\fR - ISO8601 timestamps
    \fB`unix`\fR - Unix timestamps
    \fB`now`\fR - Always set date stamp to time parsed
    \fB`None`\fR - Skip conversion

Conversion happens with any parser that has a \fBdate_stamp\fR field in \fBfields\fR (the \fBnow\fR datestamp type doesn't require a \fBdate_stamp\fR field), and adds the following attributes to the entry dictionary:

    \fByear\fR - a 4-digit string (or None)
    \fBmonth\fR - a 2-digit string
    \fBday\fR - a 2-digit string
    \fBtstamp\fR - a 6-digit string with optional decimal and extra places
    \fBtzone\fR - \fB+\fR or \fB-\fR followed by a 4-digit offset to utc (HHMM)
    \fBnumeric_date_stamp\fR - a datestamp in the form of YYYYmmddHHMMSS[.ffffff]
    \fBdate_stamp\fR - a standard date stamp (added for `now` datestamp type only)

The sojson parser has no parse_line() method.

.SH SEE ALSO
    logdissect(1)

.SH FILES
    /usr/share/doc/logdissect/README.md
    /usr/share/doc/logdissect/README-API.md
    /usr/share/doc/logdissect/README-DEV.md
    /usr/share/doc/logdissect/CHANGELOG.md
    /usr/share/doc/logdissect/LICENSE

.SH AUTHOR
    Dan Persons (dpersonsdev@gmail.com)

.SH COPYRIGHT
MIT License

Copyright (c) 2017 Dan Persons

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
